version: "3.9"

services:
  db:
    image: postgres:14.17
    container_name: postgres-theatre
    env_file:
      - .env
    environment:
      POSTGRES_DB: theatre_db
      POSTGRES_USER: theatre_user
      POSTGRES_PASSWORD: theatre_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - theatre-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  web:
    build: .
    container_name: theatre-backend
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8001:8000"

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    networks:
      - theatre-network

volumes:
  postgres_data:
    driver: local

networks:
  theatre-network:
    driver: bridge
